### ISSUE TITLE
Stash v0.10.0-rc.0 release tracker

### ISSUE THREAD

**Issue by hossainemruz** [stashed/project#2]
Issue To Fix:
- [ ] [kubectl-stash download broken](https://github.com/stashed/stash/issues/1110)
- [x] [Single BackupBatch makes stash think Repository does not exist](https://github.com/stashed/stash/issues/1113)
- [ ] Fix wait logic for the database to be ready
  - [x] MySQL
  - [x] PostgreSQL
  - [x] Elasticsearch
  - [x] MongoDB
  - [x] Percona-XtraDB
- [x] PSP
  - [x] [stash's PodSecurityPolicy is not used because of alphabetical order](https://github.com/stashed/stash/issues/910)
  - [x] [Unable to install stash 0.9.0-rc.6 in PSP-enabled cluster](https://github.com/stashed/stash/issues/1112)

Features:
- [x] Apply SecretTransform to allow to use custom secret.
  - [x] MySQL
  - [x] PostgreSQL
  - [x] Elasticsearch
  - [x] Percona-XtraDB
  - [x] MongoDB
- [ ] Introduce RestoreBatch
- [ ] Refactor BackupBatch
- [ ] Support Snapshot listing for NFS server

- [ ]  Fix NFS server tests
- [ ] Tag Stash addon's image with `-v1` suffix
- [ ] Update documentation
  - [ ] SecretTransformation
  - [ ] RestoreBatch
  - [ ] BackupConfiguration, BackupBatch, RestoreSession (alias, rules)
  - [ ] VolumeSnasphot works for v17.0.x+
  - [ ] Container name in `exec` hook
  - [ ] Point to helm installation method if the script installation does not works for the catalogs
